on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
        - os: windows-latest
        - os: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: sbt
    - run: wget https://raw.githubusercontent.com/sbt/sbt/586e0a752cd5d0f0335deaa910c4355e0e0a0e56/sbt
    - run: chmod +x ./sbt
    - run: ./sbt -v -J-Xmx4G "Jmh/run -i 10 -wi 10 -f1 -t1"
